gantt
   dateFormat  YYYY-MM-DD
   title Project schedule

   %% Documentation here: https://mermaid-js.github.io/mermaid/#/gantt

   section Frontend
   Complete Rails tutorial: crit, active, rails, 2019-12-29, 4d
   Proof-of-concept UI with React: crit, basic, after rails, 9d
   Refine UI for create/tag: crit, refine, after basic, 8d
   Add login page: crit, login, after refine, 3d
   Setup server: 2020-01-20, 5d

   section Backend
   Plan db schema: schema, after rails, 3d
   Implement task creation: create, after schema, 7d
   Implement tagging system: tag, after create, 3d
   Implement account creation: after refine, 3d
